# Generated by Django 5.2.7 on 2025-10-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='submission_date',
            new_name='delivery_date',
        ),
    ]
